---
title: "Tests"
author: "William Guesdon"
date: "01/02/2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE, message=FALSE}
################
# Load libraries
################

library(tidyverse)
library(alakazam)
library(shazam)
library(cowplot)
library(rstatix)
library(cowplot)
library(ggpubr)
```

```{r echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
#####################
#Set up ggplot theme
####################

tmp_theme <- theme_bw()

##########################################
#Set up color blind friendly color palette
##########################################

# The palette with grey:
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
# The palette with black:
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
# To use for fills, add
  # scale_fill_manual(values=cbPalette)
# To use for line and point colors, add
  # scale_colour_manual(values=cbPalette)
```

```{r}
glimpse(ExampleDb)
```


```{r}
clones <- countClones(ExampleDb, group=c("SAMPLE", "ISOTYPE"), copy="DUPCOUNT")
head(clones, 5)
```
```{r}
# Partitions the data on the SAMPLE column
# Calculates a 95% confidence interval via 200 bootstrap realizations
curve <- estimateAbundance(ExampleDb, group="SAMPLE", ci=0.95, nboot=200)
```

```{r}
# Plots a rank abundance curve of the relative clonal abundances
sample_colors <- c("-1h"="seagreen", "+7d"="steelblue")
plot(curve, colors = sample_colors, legend_title="Sample")
```

```{r}
directory <- "/Users/william/Documents/GitHub/GitHub_Data/Tipton_2015_SLE_vs_HC/Immcantation/all_samples/"
file <- dir(directory, pattern = "*.tab")
all_samples <- readChangeoDb(paste0(directory, file[1]))
glimpse(all_samples)
```

```{r}
glimpse(all_samples)
```

```{r}
# Partitions the data based on the SAMPLE column
clones <- countClones(all_samples, group="STATUS", clone = "CLONE")
head(clones, 5)
```

```{r}
# Partitions the data on the SAMPLE column
# Calculates a 95% confidence interval via 200 bootstrap realizations
curve <- estimateAbundance(all_samples, group="STATUS", ci=0.95, nboot=200)
# Plots a rank abundance curve of the relative clonal abundances
sample_colors <- c("HC"="#999999", "SLE"="#E69F00")
plot(curve, colors = sample_colors, legend_title="Sample")
```

```{r}
# Estimate abundance by sample and plot
abund <- estimateAbundance(ExampleDb, group="SAMPLE", nboot=100)
plotAbundanceCurve(abund, legend_title="Sample")
```

